---
name: tcf_getit
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  get_it_mixin: ^3.1.3
  chopper: ^4.0.3
  intl: ^0.17.0
  equatable: ^2.0.0
  font_awesome_flutter: ^9.2.0
  provider: ^6.0.1
  cached_network_image: ^3.1.0+1
  flutter_staggered_grid_view: ^0.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  chopper_generator: null
  json_serializable: null
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-LightItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf